"""
voiceover.py  —  Voiceover Generation for the Content Engine Pro
================================================================

This module handles two responsibilities:

1. SCRIPT ADAPTATION
   Converts the generated blog introduction into a voiceover-friendly
   narration script using an LLM prompt.  The adapted script has:
   - Short sentences (max 15 words each)
   - Commas for natural breathing pauses
   - Ellipses (...) for dramatic pauses
   - No visual-only references ("as you can see", "shown below", etc.)

2. AUDIO GENERATION
   Converts the adapted script to an MP3 file using Microsoft Edge TTS
   (the `edge-tts` Python package).  Edge TTS connects to Microsoft's
   text-to-speech service over the internet — it requires NO API key
   and NO Microsoft account.  It works by mimicking the same endpoint
   used by the Edge browser's built-in "Read Aloud" feature.

Public functions
----------------
adapt_script(blog_text)  ->  str
    Calls the LLM to rewrite the blog as a voiceover-friendly script.

generate_voiceover(script, output_path)  ->  str
    Calls Edge TTS and saves the result as an MP3.  Returns the file path.

create_voiceover(blog_text, output_path)  ->  tuple[str, str]
    Convenience wrapper: adapts the script then generates the audio.
    Returns (adapted_script, mp3_path).
"""

import asyncio
import os
import pathlib

import edge_tts  # pip install edge-tts

# Reuse the shared OpenRouter HTTP client — no duplicate API code
from text_gen import _call_openrouter


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# Default voice for narration.  Edge TTS supports many voices — change this
# constant to try different ones, e.g. "en-GB-SoniaNeural" (British female)
# or "en-US-GuyNeural" (American male).
DEFAULT_VOICE: str = "en-US-JennyNeural"

# Directory where MP3 files are saved.  Created automatically if missing.
AUDIO_OUTPUT_DIR: str = "generated_audio"

# Fixed filename — overwritten on every new generation so old files do not
# accumulate.  Rename to a unique path if you want to keep history.
AUDIO_FILENAME: str = "voiceover.mp3"

# ---------------------------------------------------------------------------
# LLM system prompt — Script Adapter
# ---------------------------------------------------------------------------
_SCRIPT_ADAPTER_SYSTEM = (
    "You are a professional voiceover script writer. "
    "Rewrite the blog introduction below as a natural spoken narration. "
    "Rules you must follow: "
    "- Maximum 15 words per sentence. "
    "- Add commas where a narrator would naturally breathe mid-sentence. "
    "- Use ellipses (...) for dramatic pauses between ideas. "
    "- Remove all visual references such as 'as you can see', 'shown here', "
    "'in the image above', or 'click below'. "
    "- Write in a warm, conversational tone. "
    "- Output ONLY the final narration script. "
    "No headings, no labels, no explanations."
)


# ---------------------------------------------------------------------------
# 1.  Script Adaptation  (LLM call)
# ---------------------------------------------------------------------------

def adapt_script(blog_text: str) -> str:
    """
    Rewrite a blog introduction as a voiceover-friendly narration script.

    Uses the shared _call_openrouter() helper from text_gen.py so there
    is no duplicate HTTP client code.

    Args:
        blog_text: The raw blog introduction generated by the engine.

    Returns:
        A narration-ready script string with breathing and dramatic pauses.

    Raises:
        ValueError:   If blog_text is empty.
        RuntimeError: If the LLM call fails.
    """
    # Guard: nothing to adapt if blog was not generated
    blog_text = (blog_text or "").strip()
    if not blog_text:
        raise ValueError("Cannot adapt an empty blog introduction.")

    # Trim to ~400 chars so the prompt stays compact on free-tier models
    trimmed = blog_text[:500] if len(blog_text) > 500 else blog_text
    user_prompt = f"Blog introduction to adapt:\n\n{trimmed}"

    # max_tokens=300 is enough for a ~150-word narration script
    adapted = _call_openrouter(
        _SCRIPT_ADAPTER_SYSTEM,
        user_prompt,
        max_tokens=300,
    )
    return adapted.strip()


# ---------------------------------------------------------------------------
# 2.  Audio Generation  (Edge TTS)
# ---------------------------------------------------------------------------

def generate_voiceover(
    script: str,
    output_path: str | None = None,
    voice: str = DEFAULT_VOICE,
) -> str:
    """
    Convert a voiceover script to an MP3 file using Microsoft Edge TTS.

    Edge TTS works by connecting to Microsoft's text-to-speech service —
    the same one used by the Edge browser's "Read Aloud" feature.  It
    requires an internet connection but NO API key or account.

    Args:
        script:      The narration script to convert.
        output_path: Full path for the output MP3.  Defaults to
                     AUDIO_OUTPUT_DIR/AUDIO_FILENAME.
        voice:       Edge TTS voice name (default: en-US-JennyNeural).

    Returns:
        The absolute path of the saved MP3 file.

    Raises:
        ValueError:   If script is empty.
        RuntimeError: If Edge TTS fails (e.g. no internet connection).
    """
    script = (script or "").strip()
    if not script:
        raise ValueError("Cannot generate audio from an empty script.")

    # Resolve output path — create directory if it does not exist
    if output_path is None:
        output_path = os.path.join(AUDIO_OUTPUT_DIR, AUDIO_FILENAME)

    pathlib.Path(os.path.dirname(output_path)).mkdir(parents=True, exist_ok=True)

    # Edge TTS is async — run it synchronously so the caller (Streamlit) does
    # not need to manage an event loop.
    async def _run_tts() -> None:
        tts = edge_tts.Communicate(script, voice=voice)
        await tts.save(output_path)

    try:
        asyncio.run(_run_tts())
    except Exception as exc:
        raise RuntimeError(
            f"Edge TTS audio generation failed: {exc}\n"
            "Check your internet connection and try again."
        ) from exc

    if not os.path.exists(output_path) or os.path.getsize(output_path) == 0:
        raise RuntimeError(
            "Edge TTS ran but produced an empty or missing audio file. "
            "Check your internet connection."
        )

    return os.path.abspath(output_path)


# ---------------------------------------------------------------------------
# 3.  Convenience wrapper
# ---------------------------------------------------------------------------

def create_voiceover(
    blog_text: str,
    output_path: str | None = None,
    voice: str = DEFAULT_VOICE,
) -> tuple[str, str]:
    """
    Full pipeline: adapt the blog intro, then generate an MP3.

    This is the function called from app.py.

    Args:
        blog_text:   Raw blog introduction from the campaign engine.
        output_path: Optional custom path for the MP3 file.
        voice:       Edge TTS voice name.

    Returns:
        A tuple of (adapted_script: str, mp3_path: str).

    Raises:
        ValueError:   If blog_text is empty.
        RuntimeError: If either the LLM adaptation or audio generation fails.
    """
    # Step 1 — convert blog text into a spoken narration script via LLM
    adapted_script = adapt_script(blog_text)

    # Step 2 — synthesise the narration using Edge TTS
    mp3_path = generate_voiceover(adapted_script, output_path, voice)

    return adapted_script, mp3_path
